In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('Financial Distress.csv')

In [3]:
df.columns

Index(['Company', 'Time', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9',
       'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19',
       'x20', 'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29',
       'x30', 'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39',
       'x40', 'x41', 'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49',
       'x50', 'x51', 'x52', 'x53', 'x54', 'x55', 'x56', 'x57', 'x58', 'x59',
       'x60', 'x61', 'x62', 'x63', 'x64', 'x65', 'x66', 'x67', 'x68', 'x69',
       'x70', 'x71', 'x72', 'x73', 'x74', 'x75', 'x76', 'x77', 'x78', 'x79',
       'x80', 'x81', 'x82', 'x83', 'Financial Distress'],
      dtype='object')

In [8]:
df.shape

(3672, 86)

In [5]:
e=df['Financial Distress'].value_counts()

In [9]:
e[1]/(e[0]+e[1])

0.037037037037037035

In [12]:
import pandas as pd
import numpy as np

# Import models
from pyod.models.abod import ABOD
from pyod.models.cblof import CBLOF
from pyod.models.feature_bagging import FeatureBagging
from pyod.models.hbos import HBOS
from pyod.models.iforest import IForest
from pyod.models.knn import KNN
from pyod.models.lof import LOF

In [13]:
random_state = np.random.RandomState(42)
outliers_fraction = 0.037

In [14]:
X=df.iloc[:,2:-1].values

In [15]:
y=df.iloc[:,-1].values

### Angle-based Outlier Detector (ABOD)

In [16]:
clf1=ABOD(contamination=outliers_fraction)

In [17]:
clf1.fit(X)

ABOD(contamination=0.037, method='fast', n_neighbors=5)

In [19]:
y_pred1=clf1.predict(X)

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred1)

array([[3405,  131],
       [ 133,    3]])

## Cluster-based Local Outlier Factor (CBLOF)

In [22]:
clf2=CBLOF(contamination=outliers_fraction,check_estimator=False, random_state=random_state)

In [23]:
clf2.fit(X)

CBLOF(alpha=0.9, beta=5, check_estimator=False, clustering_estimator=None,
   contamination=0.037, n_clusters=8, n_jobs=1,
   random_state=<mtrand.RandomState object at 0x7f863a5ba480>,
   use_weights=False)

In [24]:
y_pred2=clf2.predict(X)

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred2)

array([[3401,  135],
       [ 135,    1]])

## Feature Bagging

In [26]:
clf3=FeatureBagging(LOF(n_neighbors=35),contamination=outliers_fraction,check_estimator=False,random_state=random_state)

In [27]:
clf3.fit(X)

FeatureBagging(base_estimator=LOF(algorithm='auto', contamination=0.1, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=1, n_neighbors=35, p=2),
        bootstrap_features=False, check_detector=True,
        check_estimator=False, combination='average', contamination=0.037,
        estimator_params={}, max_features=1.0, n_estimators=10, n_jobs=1,
        random_state=<mtrand.RandomState object at 0x7f863a5ba480>,
        verbose=0)

In [28]:
y_pred3=clf3.predict(X)

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred3)

array([[3412,  124],
       [ 131,    5]])

## Histogram-base Outlier Detection (HBOS)

In [67]:
clf4=HBOS(alpha=0.1, contamination=0.037, n_bins=10, tol=0.9)

In [68]:
clf4.fit(X)

HBOS(alpha=0.1, contamination=0.037, n_bins=10, tol=0.9)

In [69]:
y_pred4=clf4.predict(X)

In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred4)

array([[3417,  119],
       [ 119,   17]])

## Isolation Forest

In [34]:
clf5=IForest(contamination=outliers_fraction,random_state=random_state)

In [35]:
clf5.fit(X)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/iforest.py:223: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)


IForest(behaviour='old', bootstrap=False, contamination=0.037,
    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=1,
    random_state=<mtrand.RandomState object at 0x7f863a5ba480>, verbose=0)

In [36]:
y_pred5=clf5.predict(X)

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred5)

array([[3409,  127],
       [ 127,    9]])

## K Nearest Neighbors (KNN)

In [38]:
clf6=KNN(contamination=outliers_fraction)

In [40]:
clf6.fit(X)

KNN(algorithm='auto', contamination=0.037, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [41]:
y_pred6=clf6.predict(X)

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred6)

array([[3409,  127],
       [ 133,    3]])

### Average KNN

In [43]:
clf7=KNN(method='mean',contamination=outliers_fraction)

In [44]:
clf7.fit(X)

KNN(algorithm='auto', contamination=0.037, leaf_size=30, method='mean',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [45]:
y_pred7=clf7.predict(X)

In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred7)

array([[3415,  121],
       [ 134,    2]])